name: Demo

on:
  push:
    branches:
      - master
    tags: "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.9"
      - name: check demos
        run: julia --project=docs/ docs/literateDemo.jl;
        run: if [[ $(git diff demo) ]] ; then exit 1; else exit 0; fi